{{- if .Values.platform.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-conexs.fullname" . }}-api
spec:
  replicas: {{ .Values.api.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "web-conexs.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "web-conexs.fullname" . }}-api
    spec:
      securityContext:
        runAsUser: 1000
      volumes:
        - name: data-pv-volume
          persistentVolumeClaim:
            claimName: data-pv-claim
        - emptyDir: {}
          name: tmp
      containers:
        - name: {{ include "web-conexs.fullname" . }}-api
          image:  "{{ .Values.api.deployment.image.repository }}:{{ .Values.api.deployment.image.tag | default .Chart.AppVersion }}"
          args: ["-m", "web_conexs_api"]
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
          volumeMounts:
            - mountPath: {{ .Values.data.mountPath}}
              name: data-pv-volume
            - mountPath: /tmp
              name: tmp
          env:
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.database.passwordSecretName}}
                  key: passwords
            - name: POSTGRESURL
              value: {{ .Values.database.protocol }}://{{ .Values.database.username }}:$(POSTGRESS_PASSWORD)@{{.Values.database.host | default (printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace)}}/{{ .Values.database.dbname }}
            - name: OIDC_USER_INFO_ENDPOINT
              value: {{ .Values.auth.userInfoEndpoint}}
            - name: OIDC_ID_KEY
              value: {{ .Values.auth.idKey}}
            - name: CONEXS_STORAGE_DIR
              value: {{ .Values.data.location}}
            - name: AUTHZ_CHECK
              value: {{ .Values.api.authz.type}}
            - name: LDAP_URL
              value: {{ .Values.api.authz.url}}
            - name: LDAP_BASE
              value: {{ .Values.api.authz.base}}
            - name: LDAP_ATTR_KEY
              value: {{ .Values.api.authz.key}}
            - name: LDAP_ATTR_VALUE
              value: {{ .Values.api.authz.value}}
            - name: MPLCONFIGDIR
              value: /tmp
            - name: PMG_MAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: matproj-api-key
                  key: key
{{- end }}
