{{- if .Values.platform.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-conexs.fullname" . }}-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "web-conexs.fullname" . }}-client
  template:
    metadata:
      labels:
        app: {{ include "web-conexs.fullname" . }}-client
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ include "web-conexs.fullname" . }}-client
          image: "{{ .Values.client.deployment.image.repository }}:{{ .Values.client.deployment.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8081
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
{{- end }}
